---
- name: Get list of installed plugins
  ansible.builtin.command:
    cmd: ./bin/logstash-plugin list
    chdir: "{{ logstash_dir }}"
  register: logstash_plugins_list
  changed_when: false

- name: Install configured plugins
  ansible.builtin.command:
    cmd: ./bin/logstash-plugin install {{ item }}
    chdir: "{{ logstash_dir }}"
  loop: "{{ logstash_install_plugins }}"
  when: item not in logstash_plugins_list.stdout
  notify: restart logstash
