---
- name: restart thanos sidecar
  listen:
    - restart thanos-sidecar
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: thanos-sidecar
    state: restarted
    enabled: yes

- name: reload thanos-sidecar
  listen:
    - reload thanos-sidecar
  become: true
  ansible.builtin.systemd:
    name: thanos-sidecar
    state: reloaded
