---
# handlers file for keepalived
- name: restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    daemon_reload: true
    state: restarted
    enabled: yes
    
- name: reload keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: reloaded
