---
# handlers file for consul
- name: restart consul
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: consul
    state: restarted
    enabled: yes

- name: reload consul
  become: true
  ansible.builtin.systemd:
    name: consul
    state: reloaded
