---
# tasks file for keepalived
- name: get default ip
  ansible.builtin.debug: 
    var: ansible_default_ipv4.address

- name: Install Keepalived Dependencies
  ansible.builtin.apt: 
    update_cache: yes
    name: 
      - libssl-dev
    state: present

- name: Add user keepalived_script for running script
  ansible.builtin.user: 
    name: keepalived_script
    state: present
    shell: /usr/sbin/nologin
    create_home: false

- name: Setup keepalived folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ keepalived_build_dir }}"
    - "{{ keepalived_conf_dir }}"

- name: Download keepalived tar ball
  ansible.builtin.get_url: 
    url: https://www.keepalived.org/software/keepalived-{{keepalived_version}}.tar.gz
    dest: "{{keepalived_build_dir}}/keepalived-{{keepalived_version}}.tar.gz"

- name: Unarchive keepalived tar ball
  ansible.builtin.unarchive:
    src: "{{keepalived_build_dir}}/keepalived-{{keepalived_version}}.tar.gz"
    dest: "{{keepalived_build_dir}}/"
    remote_src: yes
    extra_opts: "--strip-components=1"

- name: Configuring keepalived source with custom modules
  ansible.builtin.command: "./configure \
            --sbindir={{keepalived_sbin_dir}}"
  args:
    chdir: "{{ keepalived_build_dir }}"
  register: keepalived_configure

- name: Compile keepalived
  become: yes
  ansible.builtin.shell: make -j{{ ansible_processor_cores }} && make install
  args:
    chdir: "{{ keepalived_build_dir }}"
  when: keepalived_configure is changed
  notify:
  - restart keepalived

- name: Copy keepalived config files
  become: yes
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { src: 'keepalived.conf.j2', dest: '{{ keepalived_conf_dir }}/keepalived.conf' }
  notify:
    - restart keepalived

- name: Copy keepalived check process scripts
  become: yes
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  loop:
    - { src: 'check_nginx.sh', dest: '{{ keepalived_conf_dir }}/check_nginx.sh' }
    - { src: 'check_k8s.sh', dest: '{{ keepalived_conf_dir }}/check_k8s.sh' }    

- name: Copy systemd file
  ansible.builtin.copy:
    src: keepalived.service
    dest: /etc/systemd/system/keepalived.service
  notify:
    - restart keepalived

#- name: Clean setup folder
#  ansible.builtin.file:
#    path: "{{ keepalived_build_dir }}"
#    state: absent
