---
# handlers file for alertmanager
- name: restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    daemon_reload: true
    state: restarted
    enabled: true

- name: reload alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: reloaded
