---
- name: Ensure old versions of Docker are not installed
  ansible.builtin.yum:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Add Docker GPG key
  ansible.builtin.rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: "/etc/yum.repos.d/docker-{{ docker_edition }}.repo"
    owner: root
    group: root
    mode: '0644'
